apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: elowen
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.example.yaml
  - postgres.yaml
  - nats.yaml
  - arangodb.yaml
  - elowen-api.yaml
  - elowen-notes.yaml
  - elowen-ui.yaml
  - elowen-edge.yaml
