apiVersion: v1
kind: Secret
metadata:
  name: elowen-secrets
type: Opaque
stringData:
  POSTGRES_DB: elowen
  POSTGRES_USER: elowen
  POSTGRES_PASSWORD: elowen
  ARANGO_ROOT_PASSWORD: elowen
  ELOWEN_ARANGODB_PASSWORD: elowen
